//
// Created by i-use-gentoo-btw on 10/6/22.
//

#ifndef UNTITLEDPACKAGESCHEMEGENERATOR_CONFIG_HPP
#define UNTITLEDPACKAGESCHEMEGENERATOR_CONFIG_HPP


class Config {

};


#endif //UNTITLEDPACKAGESCHEMEGENERATOR_CONFIG_HPP
