//
// Created by i-use-gentoo-btw on 10/6/22.
//

#ifndef UNTITLEDPACKAGESCHEMEGENERATOR_EBUILDPARSER_HPP
#define UNTITLEDPACKAGESCHEMEGENERATOR_EBUILDPARSER_HPP


class EbuildParser {

};


#endif //UNTITLEDPACKAGESCHEMEGENERATOR_EBUILDPARSER_HPP
