//
// Created by i-use-gentoo-btw on 10/6/22.
//

#ifndef UNTITLEDPACKAGESCHEMEGENERATOR_DEB_HPP
#define UNTITLEDPACKAGESCHEMEGENERATOR_DEB_HPP


class deb {

};


#endif //UNTITLEDPACKAGESCHEMEGENERATOR_DEB_HPP
