//
// Created by i-use-gentoo-btw on 10/6/22.
//

#ifndef UNTITLEDPACKAGESCHEMEGENERATOR_EBUILD_HPP
#define UNTITLEDPACKAGESCHEMEGENERATOR_EBUILD_HPP


class ebuild {

};


#endif //UNTITLEDPACKAGESCHEMEGENERATOR_EBUILD_HPP
