//
// Created by i-use-gentoo-btw on 10/6/22.
//

#ifndef UNTITLEDPACKAGESCHEMEGENERATOR_FLATPAK_HPP
#define UNTITLEDPACKAGESCHEMEGENERATOR_FLATPAK_HPP


class flatpak {

};


#endif //UNTITLEDPACKAGESCHEMEGENERATOR_FLATPAK_HPP
