//
// Created by i-use-gentoo-btw on 10/6/22.
//

#ifndef UNTITLEDPACKAGESCHEMEGENERATOR_PKGBUILD_HPP
#define UNTITLEDPACKAGESCHEMEGENERATOR_PKGBUILD_HPP


class pkgbuild {

};


#endif //UNTITLEDPACKAGESCHEMEGENERATOR_PKGBUILD_HPP
