//
// Created by i-use-gentoo-btw on 10/6/22.
//

#ifndef UNTITLEDPACKAGESCHEMEGENERATOR_MSINSTALLER_HPP
#define UNTITLEDPACKAGESCHEMEGENERATOR_MSINSTALLER_HPP


class msinstaller {

};


#endif //UNTITLEDPACKAGESCHEMEGENERATOR_MSINSTALLER_HPP
