//
// Created by i-use-gentoo-btw on 10/6/22.
//

#ifndef UNTITLEDPACKAGESCHEMEGENERATOR_WINGET_HPP
#define UNTITLEDPACKAGESCHEMEGENERATOR_WINGET_HPP


class winget {

};


#endif //UNTITLEDPACKAGESCHEMEGENERATOR_WINGET_HPP
